CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE ACCOUNTS (
  EMAIL    TEXT PRIMARY KEY,
  PASSWORD TEXT NOT NULL,
  NAME     TEXT NOT NULL
);

CREATE TABLE INSTALLATIONS (
  ID   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  NAME TEXT NOT NULL
);

CREATE TABLE INSTALLATION_ACCESS (
  ACCOUNT_ID      TEXT REFERENCES ACCOUNTS (EMAIL)   NOT NULL,
  INSTALLATION_ID UUID REFERENCES INSTALLATIONS (ID) NOT NULL,
  ROL             TEXT,
  PRIMARY KEY (ACCOUNT_ID, INSTALLATION_ID, ROL)
);


CREATE TABLE NODES (
  ID              TEXT PRIMARY KEY,
  INSTALLATION_ID UUID REFERENCES INSTALLATIONS (ID) NOT NULL,
  NAME            TEXT                               NOT NULL
);

CREATE TABLE SLAVE_NODES (
  NODE_ID        TEXT PRIMARY KEY REFERENCES NODES (ID)  NOT NULL,
  MASTER_NODE_ID TEXT REFERENCES NODES (ID)              NOT NULL,
  IP             TEXT                                    NOT NULL
);


CREATE TABLE PINS (
  NODE_ID TEXT REFERENCES NODES (ID) NOT NULL,
  PIN_ID  TEXT                       NOT NULL,
  NAME    TEXT                       NOT NULL,
  TYPE    TEXT                       NOT NULL,
  MODE    TEXT                       NOT NULL,
  PRIMARY KEY (NODE_ID, PIN_ID)
);

CREATE TABLE PIN_VALUE_CHANGE_EVENTS (
  ID        UUID PRIMARY KEY            DEFAULT gen_random_uuid(),
  NODE_ID   TEXT REFERENCES NODES (ID) NOT NULL,
  PIN_ID    TEXT                       NOT NULL,
  VALUE     BOOLEAN                    NOT NULL,
  TIMESTAMP TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NODE_STATUS_CHANGE_EVENTS (
  ID        UUID PRIMARY KEY            DEFAULT gen_random_uuid(),
  NODE_ID   TEXT REFERENCES NODES (ID) NOT NULL,
  STATUS    TEXT                       NOT NULL,
  TIMESTAMP TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
